[build]
    functions = "server_functions"

[[redirects]]
    from = "/api/"
    to = "/.netlify/functions/api"
    status = 200

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/raw"
    status = 200

